"""Investigation pack writing logic."""

from __future__ import annotations

from collections import Counter
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from autopack.schema import Anomaly, Correlation, Manifest, NormalizedEvent
from autopack.utils.io import ensure_directory, write_json, write_jsonl


@dataclass(slots=True)
class PackWriteResult:
    """Result metadata for a completed pack write."""

    output_dir: Path
    files_written: list[str]


def write_investigation_pack(
    output_dir: Path,
    manifest: Manifest,
    timeline: Sequence[NormalizedEvent],
    anomalies: Sequence[Anomaly],
    correlations: Sequence[Correlation],
    summary_markdown: str,
    source_artifacts: Mapping[str, Sequence[dict[str, Any]]] | None = None,
    pattern_collapses: Sequence[dict[str, Any]] | None = None,
) -> PackWriteResult:
    """Write a deterministic incident pack to disk."""
    manifest.validate()

    for event in timeline:
        event.validate()
    for anomaly in anomalies:
        anomaly.validate()
    for correlation in correlations:
        correlation.validate()

    ensure_directory(output_dir)
    ensure_directory(output_dir / "sources")
    ensure_directory(output_dir / "evidence")

    files_written: list[str] = []

    write_json(output_dir / "manifest.json", manifest.to_dict())
    files_written.append("manifest.json")

    write_jsonl(output_dir / "timeline.jsonl", (event.to_dict() for event in timeline))
    files_written.append("timeline.jsonl")

    write_jsonl(output_dir / "anomalies.jsonl", (item.to_dict() for item in anomalies))
    files_written.append("anomalies.jsonl")

    write_jsonl(output_dir / "correlations.jsonl", (item.to_dict() for item in correlations))
    files_written.append("correlations.jsonl")

    for relative, rows in sorted((source_artifacts or {}).items()):
        if not relative or "/" in relative or "\\" in relative:
            raise ValueError("source artifact names must be simple filenames under sources/")

        write_jsonl(output_dir / "sources" / relative, rows)
        files_written.append(f"sources/{relative}")

    (output_dir / "summary.md").write_text(
        summary_markdown.strip() + "\n", encoding="utf-8", newline="\n"
    )
    files_written.append("summary.md")

    (output_dir / "SESSION.md").write_text(
        _build_session_note(manifest), encoding="utf-8", newline="\n"
    )
    files_written.append("SESSION.md")

    (output_dir / "DATA_FORMAT.md").write_text(
        _build_data_format_note(), encoding="utf-8", newline="\n"
    )
    files_written.append("DATA_FORMAT.md")

    (output_dir / "INVESTIGATION_GUIDE.md").write_text(
        _build_investigation_guide(), encoding="utf-8", newline="\n"
    )
    files_written.append("INVESTIGATION_GUIDE.md")

    write_json(
        output_dir / "evidence" / "top_patterns.json",
        _build_top_patterns(anomalies, pattern_collapses),
    )
    files_written.append("evidence/top_patterns.json")

    write_json(
        output_dir / "evidence" / "timeline_windows.json",
        _build_timeline_windows(anomalies, correlations),
    )
    files_written.append("evidence/timeline_windows.json")

    write_json(
        output_dir / "evidence" / "root_cause_candidates.json",
        _build_root_cause_candidates(correlations),
    )
    files_written.append("evidence/root_cause_candidates.json")

    return PackWriteResult(output_dir=output_dir, files_written=files_written)


def _build_session_note(manifest: Manifest) -> str:
    return "\n".join(
        [
            "# Session",
            "",
            f"- Session ID: `{manifest.session_id}`",
            f"- Pack version: `{manifest.pack_version}`",
            f"- Generated by: `{manifest.generator}`",
            f"- Created at (UTC): `{manifest.to_dict()['created_at']}`",
            f"- Sources: `{len(manifest.source_files)}`",
            "",
        ]
    )


def _build_data_format_note() -> str:
    return "\n".join(
        [
            "# Data Format",
            "",
            "AutoPack keeps both machine-readable and human-readable artifacts in one directory:",
            "",
            "- `manifest.json`: pack metadata, source hashes, and aggregate counts",
            "- `timeline.jsonl`: normalized event stream",
            "- `anomalies.jsonl`: deterministic anomaly windows",
            "- `correlations.jsonl`: cross-source correlated windows",
            "- `summary.md`: concise human summary",
            "",
        ]
    )


def _build_investigation_guide() -> str:
    return "\n".join(
        [
            "# Investigation Guide",
            "",
            "1. Start with `summary.md` for the high-level incident narrative.",
            "2. Inspect `anomalies.jsonl` for top failure windows and event IDs.",
            "3. Use `correlations.jsonl` to connect events across sources.",
            "4. Dive into `timeline.jsonl` for full event-level evidence.",
            "5. Validate integrity with `autopack validate-pack`.",
            "",
        ]
    )


def _build_top_patterns(
    anomalies: Sequence[Anomaly],
    pattern_collapses: Sequence[dict[str, Any]] | None,
) -> dict[str, object]:
    counter = Counter(item.kind for item in anomalies)
    payload: dict[str, object] = {
        "total_anomalies": len(anomalies),
        "top_anomaly_kinds": [
            {"kind": kind, "count": count} for kind, count in counter.most_common(10)
        ],
    }

    collapsed = list(pattern_collapses or [])
    payload["total_collapsed_patterns"] = len(collapsed)
    payload["collapsed_patterns"] = collapsed
    return payload


def _build_timeline_windows(
    anomalies: Sequence[Anomaly],
    correlations: Sequence[Correlation],
) -> dict[str, object]:
    return {
        "anomaly_windows": [
            {
                "anomaly_id": item.anomaly_id,
                "kind": item.kind,
                "start_time": item.to_dict()["start_time"],
                "end_time": item.to_dict()["end_time"],
            }
            for item in anomalies
        ],
        "correlation_windows": [
            {
                "correlation_id": item.correlation_id,
                "rule": item.rule,
                "window_start": item.to_dict()["window_start"],
                "window_end": item.to_dict()["window_end"],
                "confidence": item.confidence,
            }
            for item in correlations
        ],
    }


def _build_root_cause_candidates(
    correlations: Sequence[Correlation],
) -> dict[str, object]:
    ordered = sorted(correlations, key=lambda item: item.confidence, reverse=True)
    return {
        "candidates": [
            {
                "rank": index,
                "correlation_id": item.correlation_id,
                "summary": item.summary,
                "confidence": item.confidence,
                "rule": item.rule,
            }
            for index, item in enumerate(ordered, start=1)
        ]
    }
